### ISSUE TITLE
Large Recovery Index Gap

### ISSUE THREAD

**Issue by crimsonleaf363** [minibits-cash/minibits_wallet#125]
# Description:
When scanning multiple recovery intervals, the app communicated that already spent ecash had been found, followed by a series of "no Ecash found" messages, before eventually locating the ecash.

# Steps to Reproduce:
This happens during a recovery scan in the on boarding. 

1. Start a recovery scan.
2. The app prompts with "Good news is already spent Ecash has been found. Continue with next recovery interval."
3. Continue scanning the next intervals, receiving "no ecash found" messages.
4. After several scans, the app locates the ecash.

# Expected Behavior:
The app should accurately report the presence or absence of ecash without requiring multiple manual scans.

**Comment by minibits-cash** [comment]
The situation you encountered means that while using the wallet, you likely used manual increase of recovery indexes (Settings > Recovery > Increase indexes).

That caused the gap you've seen, because no ecash has been generated using skipped interval.

Tha fact that Minibits recovers in batches by 50 manually is for now necessary because of very slow related cryptographic operations on React native - when compared how they run in browser. Fully automated process would be therefore risky.

In case of long or unclear proof history I for now can recommend browser based recoveries in cashu.me or nutstash.app wallets.
