### ISSUE TITLE
LN address changed from custom to random after update or recovery

### ISSUE THREAD

**Issue by GitKalle** [minibits-cash/minibits_wallet#69]
Hello,

I donate for my custom LN address on version v0.1.6. After update to v0.1.7 my custom LN address changed to a random. Then I tried to enter my donated LN address and get the information this address is available and I have to make a donation of 500 SATs.

Is it possible to recover my LN address?

Edit1:
Two weeks before update I recover my wallet. I don't know if my LN address was recovered too.

I decided to donate the 500 SATs for the LN address again because I would like to support the development of Minibits. Good job team.

Edit2:
After OTA from v0.1.7 beta5 to 0.1.7 beta12 my LN address changes again to random.

Any suggestion?

**Comment by minibits-cash** [comment]
Unfortunately, there are cases where data migrations related to upgrade to v0.1.7 failed. Not happy about that and sorry for troubles, it simply did not happen while testing (More then once tried on 4 different brand devices).

I'll try to help with minimizing the impacts with general procedure to try to get sats and wallet address back:

1. Update to last version beta.13 version - I've released it as a native APK + Google Play release as well, because it prevents the loss of lightning address even in case, that migration fail and wallet state shows no balances
2. Go to Backup and Recovery > Recovery tool - You should see backed up ecash proofs. Local backup in separate database intends to cover cases, when wallet's primary storage gets corrupted. Try recover back to wallet. 
3. If it fails for some reason, copy proofs as encoded tokens instead. This is the ecash backup in format, that can be one by one received to any other ecash wallet. As it needs to be copied and pasted multiple times, best option is to move them to the PC, and import them to some web wallet, e.g. wallet.cashu.me.
4. In case user had turned the backup off (default is on) and it is not available, last resort is recovery of ecash using the seed. There are some reports that recovery returns errors, I will investigate it shortly - until then I suggest to recover from another wallet.
